### ISSUE TITLE
mixer module not available (ModuleNotFoundError: No module named 'pygame.mixer')

### ISSUE THREAD

**Issue by zy660622** [CharlesPikachu/Games#21]
一直报错找不到mixer这个module，我用的是Mac，需要额外安装mixer吗
Hello from the pygame community. https://www.pygame.org/contribute.html
/Users/yangzho2/Downloads/Games-master/Game12/Game12.py:283: RuntimeWarning: use mixer: No module named 'pygame.mixer'
(ModuleNotFoundError: No module named 'pygame.mixer')
  pygame.mixer.init()
Traceback (most recent call last):
  File "/Users/yangzho2/Downloads/Games-master/Game12/Game12.py", line 301, in <module>
    main()
  File "/Users/yangzho2/Downloads/Games-master/Game12/Game12.py", line 283, in main
    pygame.mixer.init()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pygame/__init__.py", line 100, in __getattr__
    raise NotImplementedError(missing_msg)
NotImplementedError: mixer module not available (ModuleNotFoundError: No module named 'pygame.mixer')

**Comment by CharlesPikachu** [comment]
refer #12，or just delete this line of code (i.e. pygame.mixer.init())
