### ISSUE TITLE
Importing Levels

### ISSUE THREAD

**Issue by Arvind232** [CharlesPikachu/Games#29]
Hi..
Hello from the pygame community. https://www.pygame.org/contribute.html
Traceback (most recent call last):
  File "c:/Users/arvin/Desktop/Pacman/game.py", line 181, in <module>
    main(initialize())
  File "c:/Users/arvin/Desktop/Pacman/game.py", line 164, in main    
    pygame.mixer.music.load(BGMPATH)
pygame.error: Failed loading libmpg123.dll: Attempt to access invalid address.

**Comment by CharlesPikachu** [comment]
try to restart your PC, or upgrade the version of pygame
