### ISSUE TITLE
Game 2 pyaudio error

### ISSUE THREAD

**Issue by mikelty** [CharlesPikachu/Games#30]
I got the following error on python3.6.8 running game 2:
Traceback (most recent call last):
  File "Game2.py", line 75, in <module>
    cocos.director.director.init(caption="Pikachu Go Go Go")
  File "C:\Users\mik\AppData\Local\Programs\Python\Python36\lib\site-packages\cocos\director.py", line 356, in init
    cocos.audio.initialize(audio_settings)
  File "C:\Users\mik\AppData\Local\Programs\Python\Python36\lib\site-packages\cocos\audio\__init__.py", line 58, in initialize
    music.set_control('dummy')
I asked around and someone said the audio needs to be initialized and gave the docs: http://python.cocos2d.org/doc/api/cocos.director.html#cocos.director.Director.init .
I'm a beginner to cocos so I don't know how to fix this. Help please.

**Comment by CharlesPikachu** [comment]
you need to install the specified cocos version.
